# Generated by Django 5.0.4 on 2024-04-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivymeshuser',
            name='role',
            field=models.CharField(blank=True, max_length=150, verbose_name='role'),
        ),
    ]
