# Generated by Django 5.0.4 on 2024-05-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ivymeshuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IvyMeshUser',
        ),
    ]
