# Generated by Django 5.0.4 on 2024-04-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=10)),
                ('instruction_mode', models.CharField(max_length=12)),
                ('part_of_term', models.CharField(max_length=15)),
                ('credits', models.IntegerField(max_length=1)),
                ('campus', models.CharField(max_length=20)),
                ('days', models.DateTimeField()),
                ('location', models.CharField(max_length=10)),
            ],
        ),
    ]
